In [1]:
# import dependencies

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np


# may delete or move these these once model is more defined
#  moved down to split section-> from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [2]:
# import data and create dataframe
# current path uses preliminary accident file and not real data output including vehicles
data = Path('Resources/accident.csv')
df_un = pd.read_csv(data)
df_un.head(30)

CASENUM  STRATUM                               STRATUMNAME  REGION  \
0   202002121240        9   Stratum 9 - LMY PV No Injuries in Crash       4   
1   202002121829        8          Stratum 8 - NLMY PV Minor Injury       3   
2   202002121849        9   Stratum 9 - LMY PV No Injuries in Crash       3   
3   202002123484       10                        Stratum 10 - Other       4   
4   202002123576       10                        Stratum 10 - Other       1   
5   202002125146        8          Stratum 8 - NLMY PV Minor Injury       2   
6   202002125149       10                        Stratum 10 - Other       2   
7   202002125582        7              Stratum 7 - M/H Truck or Bus       3   
8   202002125605       10                        Stratum 10 - Other       3   
9   202002125637       10                        Stratum 10 - Other       3   
10  202002125644        7              Stratum 7 - M/H Truck or Bus       3   
11  202002125680        8          Stratum 8 - NLMY PV Minor Injury       3   
12  202002125788        9   Stratum 9 - LMY PV No Injuries in Crash       3   
13  202002125838        3         Stratum 3 - Motorcycle Any Injury       3   
14  202002125923        9   Stratum 9 - LMY PV No Injuries in Crash       3   
15  202002125942       10                        Stratum 10 - Other       3   
16  202002125952        2  Stratum 2 - Not a MV Occupant Any Injury       3   
17  202002126030        5        Stratum 5 - NLMY PV Serious Injury       3   
18  202002126041       10                        Stratum 10 - Other       3   
19  202002126048        7              Stratum 7 - M/H Truck or Bus       3   
20  202002126072        8          Stratum 8 - NLMY PV Minor Injury       3   
21  202002126111       10                        Stratum 10 - Other       3   
22  202002126123        9   Stratum 9 - LMY PV No Injuries in Crash       3   
23  202002126132       10                        Stratum 10 - Other       3   
24  202002126138        9   Stratum 9 - LMY PV No Injuries in Crash       1   
25  202002126317        8          Stratum 8 - NLMY PV Minor Injury       3   
26  202002126335       10                        Stratum 10 - Other       3   
27  202002126339        6           Stratum 6 - LMY PV Minor Injury       3   
28  202002126362       10                        Stratum 10 - Other       3   
29  202002126381        9   Stratum 9 - LMY PV No Injuries in Crash       3   

                                           REGIONNAME  PSU    PJ  PSU_VAR  \
0   West (MT, ID, WA, OR, CA, NV, NM, AZ, UT, CO, ...   20  4140       20   
1   South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   28  4139       28   
2   South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   12  4142       12   
3   West (MT, ID, WA, OR, CA, NV, NM, AZ, UT, CO, ...   20  4140       20   
4      Northeast (PA, NJ, NY, NH, VT, RI, MA, ME, CT)   22  4149       22   
5   Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, I...   77  4151       77   
6   Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, I...   77  4151       77   
7   South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   63  4135       63   
8   South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   35  4141       35   
9   South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   32  4145       32   
10  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   32  4145       32   
11  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   83  4148       83   
12  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   59  4137       59   
13  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   59  4137       59   
14  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   28  4139       28   
15  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   28  4139       28   
16  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   28  4139       28   
17  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   12  4142       12   
18  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   12  4142       12   
19  South (MD, DE, 

In [3]:
#filter dataframe to remove unknows categories
df = df_un[df_un['MAX_SEV'] < 5]
df.head(30)

CASENUM  STRATUM                               STRATUMNAME  REGION  \
0   202002121240        9   Stratum 9 - LMY PV No Injuries in Crash       4   
1   202002121829        8          Stratum 8 - NLMY PV Minor Injury       3   
2   202002121849        9   Stratum 9 - LMY PV No Injuries in Crash       3   
3   202002123484       10                        Stratum 10 - Other       4   
4   202002123576       10                        Stratum 10 - Other       1   
5   202002125146        8          Stratum 8 - NLMY PV Minor Injury       2   
7   202002125582        7              Stratum 7 - M/H Truck or Bus       3   
8   202002125605       10                        Stratum 10 - Other       3   
9   202002125637       10                        Stratum 10 - Other       3   
10  202002125644        7              Stratum 7 - M/H Truck or Bus       3   
11  202002125680        8          Stratum 8 - NLMY PV Minor Injury       3   
12  202002125788        9   Stratum 9 - LMY PV No Injuries in Crash       3   
13  202002125838        3         Stratum 3 - Motorcycle Any Injury       3   
14  202002125923        9   Stratum 9 - LMY PV No Injuries in Crash       3   
15  202002125942       10                        Stratum 10 - Other       3   
16  202002125952        2  Stratum 2 - Not a MV Occupant Any Injury       3   
17  202002126030        5        Stratum 5 - NLMY PV Serious Injury       3   
18  202002126041       10                        Stratum 10 - Other       3   
19  202002126048        7              Stratum 7 - M/H Truck or Bus       3   
20  202002126072        8          Stratum 8 - NLMY PV Minor Injury       3   
21  202002126111       10                        Stratum 10 - Other       3   
22  202002126123        9   Stratum 9 - LMY PV No Injuries in Crash       3   
23  202002126132       10                        Stratum 10 - Other       3   
24  202002126138        9   Stratum 9 - LMY PV No Injuries in Crash       1   
25  202002126317        8          Stratum 8 - NLMY PV Minor Injury       3   
26  202002126335       10                        Stratum 10 - Other       3   
27  202002126339        6           Stratum 6 - LMY PV Minor Injury       3   
28  202002126362       10                        Stratum 10 - Other       3   
29  202002126381        9   Stratum 9 - LMY PV No Injuries in Crash       3   
30  202002126415       10                        Stratum 10 - Other       3   

                                           REGIONNAME  PSU    PJ  PSU_VAR  \
0   West (MT, ID, WA, OR, CA, NV, NM, AZ, UT, CO, ...   20  4140       20   
1   South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   28  4139       28   
2   South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   12  4142       12   
3   West (MT, ID, WA, OR, CA, NV, NM, AZ, UT, CO, ...   20  4140       20   
4      Northeast (PA, NJ, NY, NH, VT, RI, MA, ME, CT)   22  4149       22   
5   Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, I...   77  4151       77   
7   South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   63  4135       63   
8   South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   35  4141       35   
9   South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   32  4145       32   
10  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   32  4145       32   
11  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   83  4148       83   
12  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   59  4137       59   
13  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   59  4137       59   
14  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   28  4139       28   
15  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   28  4139       28   
16  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   28  4139       28   
17  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   12  4142       12   
18  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   12  4142       12   
19  South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...   75  4144       75   
20  South (MD, DE, 

In [4]:
# separate targets

y = df["MAX_SEV"]
y.tail(5)


54740    2
54741    1
54742    2
54743    0
54744    0
Name: MAX_SEV, dtype: int64

In [5]:
#create resulting features dataframe
X_df = df[["REGION","URBANICITY","MONTH","YEAR","DAY_WEEK","HARM_EV","ALCOHOL","MAN_COLL","RELJCT1","RELJCT2","TYP_INT","WRK_ZONE","REL_ROAD","LGT_COND","INT_HWY","WEATHER"]]
X_df.tail(5)

REGION  URBANICITY  MONTH  YEAR  DAY_WEEK  HARM_EV  ALCOHOL  MAN_COLL  \
54740       3           2     12  2020         4       52        2         0   
54741       3           1     11  2020         5       11        2         0   
54742       3           1     11  2020         3       34        9         0   
54743       3           1     11  2020         2       12        2         6   
54744       3           1     12  2020         2       12        2         6   

       RELJCT1  RELJCT2  TYP_INT  WRK_ZONE  REL_ROAD  LGT_COND  INT_HWY  \
54740        0        1        1         0         4         1        0   
54741        0        1        1         0         1         2        0   
54742        0        1        1         0         4         1        0   
54743        1        2        2         0         1         2        0   
54744        0        8        1         0         1         8        0   

       WEATHER  
54740       10  
54741        1  
54742        1  
54743        1  
54744        1

In [6]:
# partition data into training and test data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, 
                                                    y, random_state =1,test_size = .2)
X_train.shape

(42833, 16)

In [7]:
#Resample the training data to account for variations in the sampe
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

In [8]:
# create the model
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100)

In [9]:
# train the model *can toggle between resampled data
classifier.fit(X_resampled, y_resampled)
#classifier.fit(X_train, y_train)

RandomForestClassifier()

In [10]:
# make preditions with the model
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

Prediction  Actual
0            1       1
1            0       4
2            3       2
3            0       1
4            0       1
5            1       0
6            4       2
7            1       1
8            3       1
9            3       3
10           0       0
11           2       1
12           0       0
13           0       0
14           2       0
15           0       2
16           3       4
17           1       0
18           0       0
19           1       1

In [11]:
# export results to a csv file
df_results=pd.DataFrame(results)
df_results.to_csv('results_no_veh.csv')

In [12]:
# validate the model

In [13]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.40993556821365207


In [14]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[2880  854  551  360   78]
 [ 985  642  525  297   60]
 [ 633  396  533  285   71]
 [ 353  265  279  307   68]
 [  69   45   59   86   28]]


In [15]:
# export confusion matrix to a csv file
df_matrix=pd.DataFrame(matrix)
df_matrix.to_csv('matrix_no_veh.csv')

In [16]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.59      0.61      0.60      4723
           1       0.29      0.26      0.27      2509
           2       0.27      0.28      0.28      1918
           3       0.23      0.24      0.24      1272
           4       0.09      0.10      0.09       287

    accuracy                           0.41     10709
   macro avg       0.29      0.30      0.30     10709
weighted avg       0.41      0.41      0.41     10709



In [17]:
#