In [1]:
# import dependencies

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np


# may delete or move these these once model is more defined
#  moved down to split section-> from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [2]:
# import data and create dataframe
# current path uses preliminary accident file and not real data output including vehicles
data = Path('Resources/combo_prod.csv')
df_un = pd.read_csv(data)
df_un.head(30)

CASENUM  VEH_NO  STRATUM  VE_FORMS  NUMOCCS NUMOCCSNAME MONTHNAME  \
0   '202002121240       1        9         2        1           1   January   
1   '202002121240       2        9         2        1           1   January   
2   '202002121829       1        8         1        1           1   January   
3   '202002121849       1        9         2       99     Unknown   January   
4   '202002121849       2        9         2        1           1   January   
5   '202002125680       1        8         2        1           1   January   
6   '202002123484       1       10         1        1           1   January   
7   '202002123576       1       10         1        2           2   January   
8   '202002125146       1        8         1        2           2   January   
9   '202002125149       1       10         1        1           1   January   
10  '202002125582       1        7         3        1           1   January   
11  '202002125582       2        7         3        2           2   January   
12  '202002125582       3        7         3        1           1   January   
13  '202002125605       1       10         1        1           1   January   
14  '202002125637       1       10         1        3           3   January   
15  '202002125644       1        7         1        1           1   January   
16  '202002125680       2        8         2        2           2   January   
17  '202002125788       1        9         2        1           1   January   
18  '202002125788       2        9         2        2           2   January   
19  '202002125838       1        3         2        1           1   January   
20  '202002125838       2        3         2        2           2   January   
21  '202002125923       1        9         2        1           1   January   
22  '202002125923       2        9         2        1           1   January   
23  '202002125942       1       10         2        3           3   January   
24  '202002125942       2       10         2        1           1   January   
25  '202002125952       1        2         1        1           1   January   
26  '202002126030       1        5         2        1           1   January   
27  '202002126317       1        8         2        1           1   January   
28  '202002126030       2        5         2        5           5   January   
29  '202002126041       1       10         1        2           2   January   

    HARM_EV                          HARM_EVNAME  MAN_COLL  ... INT_HWY  \
0        12           Motor Vehicle In-Transport         6  ...       0   
1        12           Motor Vehicle In-Transport         6  ...       0   
2        42                 Tree (Standing Only)         0  ...       0   
3        12           Motor Vehicle In-Transport         1  ...       0   
4        12           Motor Vehicle In-Transport         1  ...       0   
5        12           Motor Vehicle In-Transport         1  ...       1   
6        57                        Cable Barrier         0  ...       1   
7         1                    Rollover/Overturn         0  ...       0   
8        34                                Ditch         0  ...       0   
9        11                          Live Animal         0  ...       0   
10       12           Motor Vehicle In-Transport         6  ...       0   
11       12           Motor Vehicle In-Transport         6  ...       0   
12       12           Motor Vehicle In-Transport         6  ...       0   
13        1                    Rollover/Overturn         0  ...       0   
14        1                    Rollover/Overturn         0  ...       0   
15       52                        Guardrail End         0  ...       1   
16       12           Motor Vehicle In-Transport         1  ...       1   
17       12           Motor Vehicle In-Transport         1  ...       0   
18       12           Motor Vehicle In-Transport         1  ...       0   
19       12           Motor Vehicle In-Transport         6  

In [3]:
#filter dataframe to remove unknows categories
df = df_un[df_un['MAX_SEV'] < 5]
df.head(30)

CASENUM  VEH_NO  STRATUM  VE_FORMS  NUMOCCS NUMOCCSNAME MONTHNAME  \
0   '202002121240       1        9         2        1           1   January   
1   '202002121240       2        9         2        1           1   January   
2   '202002121829       1        8         1        1           1   January   
3   '202002121849       1        9         2       99     Unknown   January   
4   '202002121849       2        9         2        1           1   January   
5   '202002125680       1        8         2        1           1   January   
6   '202002123484       1       10         1        1           1   January   
7   '202002123576       1       10         1        2           2   January   
8   '202002125146       1        8         1        2           2   January   
10  '202002125582       1        7         3        1           1   January   
11  '202002125582       2        7         3        2           2   January   
12  '202002125582       3        7         3        1           1   January   
13  '202002125605       1       10         1        1           1   January   
14  '202002125637       1       10         1        3           3   January   
15  '202002125644       1        7         1        1           1   January   
16  '202002125680       2        8         2        2           2   January   
17  '202002125788       1        9         2        1           1   January   
18  '202002125788       2        9         2        2           2   January   
19  '202002125838       1        3         2        1           1   January   
20  '202002125838       2        3         2        2           2   January   
21  '202002125923       1        9         2        1           1   January   
22  '202002125923       2        9         2        1           1   January   
23  '202002125942       1       10         2        3           3   January   
24  '202002125942       2       10         2        1           1   January   
25  '202002125952       1        2         1        1           1   January   
26  '202002126030       1        5         2        1           1   January   
27  '202002126317       1        8         2        1           1   January   
28  '202002126030       2        5         2        5           5   January   
29  '202002126041       1       10         1        2           2   January   
30  '202002126048       1        7         2        2           2   January   

    HARM_EV                          HARM_EVNAME  MAN_COLL  ... INT_HWY  \
0        12           Motor Vehicle In-Transport         6  ...       0   
1        12           Motor Vehicle In-Transport         6  ...       0   
2        42                 Tree (Standing Only)         0  ...       0   
3        12           Motor Vehicle In-Transport         1  ...       0   
4        12           Motor Vehicle In-Transport         1  ...       0   
5        12           Motor Vehicle In-Transport         1  ...       1   
6        57                        Cable Barrier         0  ...       1   
7         1                    Rollover/Overturn         0  ...       0   
8        34                                Ditch         0  ...       0   
10       12           Motor Vehicle In-Transport         6  ...       0   
11       12           Motor Vehicle In-Transport         6  ...       0   
12       12           Motor Vehicle In-Transport         6  ...       0   
13        1                    Rollover/Overturn         0  ...       0   
14        1                    Rollover/Overturn         0  ...       0   
15       52                        Guardrail End         0  ...       1   
16       12           Motor Vehicle In-Transport         1  ...       1   
17       12           Motor Vehicle In-Transport         1  ...       0   
18       12           Motor Vehicle In-Transport         1  ...       0   
19       12           Motor Vehicle In-Transport         6  ...       0   
20       12           Motor Vehicle In-Transport         6  

In [4]:
# separate targets

y = df["MAX_SEV"]
y.tail(5)


94343    3
94344    0
94345    0
94346    0
94347    1
Name: MAX_SEV, dtype: int64

In [5]:
#create resulting features dataframe
X_df = df[["VEH_NO","VE_FORMS","NUMOCCS","HARM_EV","MAN_COLL","UNITTYPE","HIT_RUN","MAKE","MODEL","MAK_MOD","BODY_TYP","MOD_YEAR","TOW_VEH","J_KNIFE","TRAV_SP","ROLLOVER","ROLINLOC","DEFORMED","TOWED","M_HARM","VEH_ALCH","FIRE_EXP","DR_PRES","DR_ZIP","SPEEDREL","VTRAFWAY","VNUM_LAN","VALIGN","VPROFILE","VSURCOND","VTRAFCON","VTCONT_F","P_CRASH1","P_CRASH2","P_CRASH3","PCRASH4","PCRASH5","ACC_TYPE","VPICMAKE","VPICMODEL","VPICBODYCLASS","ICFINALBODY","GVWR_FROM","GVWR_TO","REGION","URBANICITY","MONTH","YEAR","DAY_WEEK","ALCOHOL","RELJCT1","RELJCT2","TYP_INT","WRK_ZONE","REL_ROAD","LGT_COND","INT_HWY","WEATHER"]]
X_df.tail(5)

VEH_NO  VE_FORMS  NUMOCCS  HARM_EV  MAN_COLL  UNITTYPE  HIT_RUN  MAKE  \
94343       2         2        1       12         2         1        0    99   
94344       2         2        1       12         1         1        0    49   
94345       1         2        1       12         1         1        0    52   
94346       2         2        1       12         1         1        0    37   
94347       1         3        1       12         1         1        0    12   

       MODEL  MAK_MOD  ...  DAY_WEEK  ALCOHOL  RELJCT1  RELJCT2  TYP_INT  \
94343    709    99709  ...         6        9        0        2        2   
94344    401    49401  ...         7        2        0        3        2   
94345     47    52047  ...         2        2        0        3        2   
94346     32    37032  ...         2        2        0        3        2   
94347     37    12037  ...         4        2        0        1        1   

       WRK_ZONE  REL_ROAD  LGT_COND  INT_HWY  WEATHER  
94343         0         1         1        0        1  
94344         0         1         1        0        1  
94345         0         1         1        0       10  
94346         0         1         1        0       10  
94347         0         1         1        0        1  

[5 rows x 58 columns]

In [6]:
# partition data into training and test data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, 
                                                    y, random_state =1,test_size = .2)
X_train.shape

(74485, 58)

In [7]:
#Resample the training data to account for variations in the sampe
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

In [8]:
# create the model
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100)

In [9]:
# train the model *can toggle between resampled data
#classifier.fit(X_resampled, y_resampled)
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [10]:
# make preditions with the model
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

Prediction  Actual
0            0       2
1            0       1
2            0       2
3            1       1
4            0       0
5            0       3
6            1       4
7            0       0
8            0       2
9            1       0
10           0       0
11           1       1
12           2       2
13           3       3
14           1       1
15           0       3
16           2       2
17           2       3
18           0       0
19           0       0

In [11]:
# export results to a csv file
df_results=pd.DataFrame(results)
df_results.to_csv('results_test.csv')

In [12]:
# validate the model

In [13]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.5633122113629041


In [14]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[7619  636  207  117    1]
 [2382 1356  522  157    2]
 [1236  681  977  224    4]
 [ 663  443  449  493   16]
 [ 106   57   87  142   45]]


In [15]:
# export confusion matrix to a csv file
df_matrix=pd.DataFrame(matrix)
df_matrix.to_csv('matrix_test.csv')

In [16]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.63      0.89      0.74      8580
           1       0.43      0.31      0.36      4419
           2       0.44      0.31      0.36      3122
           3       0.44      0.24      0.31      2064
           4       0.66      0.10      0.18       437

    accuracy                           0.56     18622
   macro avg       0.52      0.37      0.39     18622
weighted avg       0.53      0.56      0.53     18622



In [17]:
#